services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: linkar
      POSTGRES_PASSWORD: linkar
      POSTGRES_DB: linkar
    ports:
      - "5432:5432"
    volumes:
      - linkar-postgres:/var/lib/postgresql/data
  valkey:
    image: valkey/valkey:9.1.1-alpine3.24
    ports:
      - "6379:6379"
    volumes:
      - linkar-valkey:/data

volumes:
  linkar-postgres:
  linkar-valkey:
