"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { Archive, Plus, Save, WalletCards } from "lucide-react";

type Plan = {
  id: string; key: string; name: string; isActive: boolean; version: number; workspaceCount: number;
  memberLimit: number | null; automationLimit: number | null; instagramConnectionLimit: number | null;
  facebookConnectionLimit: number | null; sequenceLimit: number | null; monthlyBroadcastLimit: number | null; monthlyDeliveryLimit: number | null;
  sequencesEnabled: boolean; broadcastsEnabled: boolean; trackedLinksEnabled: boolean; teamEnabled: boolean; facebookEnabled: boolean; exportsEnabled: boolean;
};
type Values = Omit<Plan, "id" | "key" | "isActive" | "version" | "workspaceCount">;
const limitFields = [["memberLimit", "Members"], ["automationLimit", "Automations"], ["instagramConnectionLimit", "Instagram connections"], ["facebookConnectionLimit", "Facebook connections"], ["sequenceLimit", "Sequences"], ["monthlyBroadcastLimit", "Monthly broadcasts"], ["monthlyDeliveryLimit", "Monthly deliveries"]] as const;
const featureFields = [["sequencesEnabled", "Sequences"], ["broadcastsEnabled", "Broadcasts"], ["trackedLinksEnabled", "Tracked links"], ["teamEnabled", "Team access"], ["facebookEnabled", "Facebook"], ["exportsEnabled", "Exports"]] as const;
const defaults: Values = { name: "", memberLimit: 2, automationLimit: 3, instagramConnectionLimit: 1, facebookConnectionLimit: 0, sequenceLimit: 0, monthlyBroadcastLimit: 0, monthlyDeliveryLimit: 100, sequencesEnabled: false, broadcastsEnabled: false, trackedLinksEnabled: false, teamEnabled: false, facebookEnabled: false, exportsEnabled: false };

async function mutate(url: string, method: string, body: unknown, reason: string) { const response = await fetch(url, { method, headers: { "content-type": "application/json", "x-admin-reason": reason, "idempotency-key": `admin-${crypto.randomUUID()}` }, body: JSON.stringify(body) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error ?? "plan_operation_failed"); }

function PlanFields({ value, onChange }: { value: Values; onChange: (value: Values) => void }) {
  return <><label className="field"><span>Display name</span><input required value={value.name} onChange={(event) => onChange({ ...value, name: event.target.value })} /></label><fieldset className="admin-plan-fieldset"><legend>Resource limits</legend><p className="muted">Leave a limit empty for unlimited.</p><div className="admin-plan-limit-grid">{limitFields.map(([key, label]) => <label className="field" key={key}><span>{label}</span><input type="number" min="0" value={value[key] ?? ""} placeholder="Unlimited" onChange={(event) => onChange({ ...value, [key]: event.target.value === "" ? null : Number(event.target.value) })} /></label>)}</div></fieldset><fieldset className="admin-plan-fieldset"><legend>Features</legend><div className="admin-feature-grid">{featureFields.map(([key, label]) => <label className="admin-check-field" key={key}><input type="checkbox" checked={value[key]} onChange={(event) => onChange({ ...value, [key]: event.target.checked })} /> {label}</label>)}</div></fieldset></>;
}

function PlanEditor({ plan, onError }: { plan: Plan; onError: (message: string | null) => void }) {
  const router = useRouter(); const [value, setValue] = useState<Values>(() => { const { id: _id, key: _key, isActive: _active, version: _version, workspaceCount: _count, ...values } = plan; return values; }); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false);
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); onError(null); try { await mutate(`/api/admin/plans/${plan.id}`, "PATCH", { ...value, version: plan.version }, reason); router.refresh(); } catch (cause) { onError(cause instanceof Error ? cause.message.replaceAll("_", " ") : "Operation failed"); } finally { setBusy(false); } }
  async function retire() { setBusy(true); onError(null); try { await mutate(`/api/admin/plans/${plan.id}`, "DELETE", { version: plan.version }, reason); router.refresh(); } catch (cause) { onError(cause instanceof Error ? cause.message.replaceAll("_", " ") : "Operation failed"); } finally { setBusy(false); } }
  return <form className="panel admin-plan-card" onSubmit={save}><div className="panel-heading"><div><p className="eyebrow">{plan.key} · version {plan.version}</p><h2>{plan.name}</h2><p className="muted">{plan.workspaceCount} assigned workspaces · {plan.isActive ? "Active" : "Retired"}</p></div><span className={`status-pill is-${plan.isActive ? "active" : "suspended"}`}>{plan.isActive ? "active" : "retired"}</span></div><PlanFields value={value} onChange={setValue} /><label className="field"><span>Operator reason</span><input required minLength={3} value={reason} onChange={(event) => setReason(event.target.value)} /></label><div className="admin-command-actions"><button className="button button-primary" disabled={busy || !plan.isActive} type="submit"><Save size={16} /> Save plan</button><button className="button button-secondary" disabled={busy || !plan.isActive} type="button" onClick={retire}><Archive size={16} /> Retire plan</button></div></form>;
}

export function PlansScreen({ plans }: { plans: Plan[] }) {
  const router = useRouter(); const [creating, setCreating] = useState(false); const [key, setKey] = useState(""); const [value, setValue] = useState(defaults); const [reason, setReason] = useState(""); const [error, setError] = useState<string | null>(null);
  async function create(event: FormEvent) { event.preventDefault(); setCreating(true); setError(null); try { await mutate("/api/admin/plans", "POST", { key, ...value }, reason); setKey(""); setValue(defaults); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message.replaceAll("_", " ") : "Operation failed"); } finally { setCreating(false); } }
  return <main className="page-wrap admin-resource-page"><header className="page-header"><div><p className="eyebrow">Linkar operator / entitlements</p><h1>Plans and limits</h1><p className="muted page-lede">Define enforceable templates. Empty limits mean unlimited; retired plans remain attached to existing workspaces.</p></div><span className="admin-count-badge"><WalletCards size={16} /> {plans.length} templates</span></header>{error ? <div className="form-error" role="alert">{error}</div> : null}<form className="panel admin-plan-card admin-new-plan" onSubmit={create}><div className="panel-heading"><div><p className="eyebrow">New template</p><h2>Create plan</h2></div><Plus size={20} /></div><label className="field"><span>Stable key</span><input required pattern="[a-z][a-z0-9_-]{1,39}" value={key} onChange={(event) => setKey(event.target.value)} placeholder="growth" /></label><PlanFields value={value} onChange={setValue} /><label className="field"><span>Operator reason</span><input required minLength={3} value={reason} onChange={(event) => setReason(event.target.value)} /></label><button className="button button-primary" disabled={creating} type="submit"><Plus size={16} /> Create plan</button></form><section className="admin-plan-stack" aria-label="Plan templates">{plans.map((plan) => <PlanEditor key={plan.id} plan={plan} onError={setError} />)}</section></main>;
}
