import { beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ read: vi.fn(), write: vi.fn(), load: vi.fn(), update: vi.fn(), audit: vi.fn() }));
vi.mock("server-only", () => ({}));
vi.mock("@/src/lib/admin/request-guard", () => ({ requireAdminRead: mocks.read, requireAdminWrite: mocks.write }));
vi.mock("@/src/lib/admin/plan-service", () => ({ loadAdminWorkspaceEntitlement: mocks.load, updateAdminWorkspaceEntitlement: mocks.update }));
vi.mock("@/src/lib/admin/audit", () => ({ appendAdminAuditEvent: mocks.audit }));
const { PATCH } = await import("./route");
const context = { owner: { userId: "owner", email: "owner@linkar.in", sessionId: "s", aal: "aal2" }, action: "workspace.entitlement.update", targetType: "workspace", targetId: "w1", reason: "Customer upgrade", idempotencyKey: "admin-plan-assign", requestId: "r", origin: "https://app.linkar.in", ipHash: "h", userAgent: "test" };
describe("workspace entitlement route", () => { beforeEach(() => { mocks.write.mockReset().mockResolvedValue(context); mocks.update.mockReset().mockResolvedValue({ workspaceId: "w1", version: 3 }); mocks.audit.mockReset().mockResolvedValue(undefined); }); it("passes strict override and version data", async () => { const body = { planId: "p1", overrides: { automationLimit: 50, exportsEnabled: true }, version: 2 }; const response = await PATCH(new Request("https://app.linkar.in/api/admin/workspaces/w1/entitlement", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }), { params: Promise.resolve({ workspaceId: "w1" }) }); expect(response.status).toBe(200); expect(mocks.update).toHaveBeenCalledWith("w1", body); }); it("rejects undocumented override keys", async () => { const response = await PATCH(new Request("https://app.linkar.in/api/admin/workspaces/w1/entitlement", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ planId: "p1", overrides: { secretLimit: 10 }, version: 2 }) }), { params: Promise.resolve({ workspaceId: "w1" }) }); expect(response.status).toBe(422); }); });
