"use client";

import Link from "next/link";
import { useState } from "react";

type Event = { id: string; requestId: string; phase: string; actorEmail: string; action: string; targetType: string; targetId: string; workspaceId: string | null; reason: string; before: unknown; after: unknown; errorCode: string | null; origin: string | null; createdAt: Date | string };

export function AuditConsole({ events, nextHref, filters }: { events: Event[]; nextHref: string | null; filters: Record<string, string> }) {
  const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false);
  async function exportCsv() { setBusy(true); try { const response = await fetch("/api/admin/audit/export", { method: "POST", headers: { "content-type": "application/json", "x-admin-reason": reason, "idempotency-key": `audit-export-${crypto.randomUUID()}` }, body: JSON.stringify(filters) }); if (!response.ok) throw new Error("Export failed"); const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "linkar-audit.csv"; anchor.click(); URL.revokeObjectURL(url); } finally { setBusy(false); } }
  return <main className="page-wrap admin-resource-page"><header className="page-header"><div><p className="eyebrow">Linkar operator / accountability</p><h1>Immutable audit trail</h1><p className="muted page-lede">Every privileged attempt, success, and failure in descending event order.</p></div></header><form className="panel admin-filter-bar"><label>Actor<input name="actor" defaultValue={filters.actor} /></label><label>Action<input name="action" defaultValue={filters.action} /></label><label>Phase<select name="phase" defaultValue={filters.phase}><option value="">All</option><option>ATTEMPT</option><option>SUCCESS</option><option>FAILURE</option></select></label><button className="button button-secondary" type="submit">Apply filters</button></form><section className="panel"><div className="admin-audit-export"><label>Export reason<input value={reason} onChange={(event) => setReason(event.target.value)} /></label><button className="button button-secondary" disabled={busy || reason.trim().length < 3} onClick={() => void exportCsv()}>Export safe CSV</button></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Target</th><th>Result</th><th>Details</th></tr></thead><tbody>{events.map((event) => <tr key={event.id}><td>{new Date(event.createdAt).toLocaleString()}<small>{event.requestId}</small></td><td>{event.actorEmail}</td><td>{event.action}</td><td>{event.targetType}<small>{event.targetId}</small></td><td>{event.phase}{event.errorCode ? <small>{event.errorCode}</small> : null}</td><td><details><summary>Redacted summary</summary><p>{event.reason}</p><pre>{JSON.stringify({ before: event.before, after: event.after }, null, 2)}</pre></details></td></tr>)}</tbody></table></div>{nextHref ? <Link className="button button-secondary" href={nextHref}>Older events</Link> : null}</section></main>;
}
